version: '3.9'

services:
  app:
    build:
      context: .
      target: dev
      args:
        NODE_VERSION: 18
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0

  prod:
    build:
      context: .
      target: prod
      args:
        NODE_VERSION: 18
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
