version: '3.9'

services:
  app:
    build:
      context: .
      target: dev
      args:
        NODE_VERSION: 18
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:4000/graphql
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  postgres-audit:
    image: postgres:16
    container_name: audit-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smartmenu_audit
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - audit-data:/var/lib/postgresql/data

  prod:
    build:
      context: .
      target: prod
      args:
        NODE_VERSION: 18
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production

volumes:
  mongo-data:
  audit-data:
